<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Models\Product;
use Carbon\Carbon;
class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $values = array(
            //T-Shirt
            array(
                'sku'=>'SL221101M',
                'product_name'=>'Sport Vintage T-Shirt',
                'description'=> 'SAINT LAURENT has been influencing and revolutionizing the fashion industry since the debut of its iconic "Rive Gauche" collection in 1966 - the couture house was the first to create a ready-to-wear capsule. The sleek, precisely tailored staples, like the signature biker jackets, transcend seasons and trends. Creative Director Anthony Vaccarello continues to honor the label"s illustrious reputation by reintroducing cult styles, including the "Lou" handbag and "Tribute" sandals.',
                'price'=>550,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/SL221101M.jpg',
                'categories' => 1,
                'product_type' => 1,
                'supplier' => 10,
                'brand'=> 10,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                'sku'=>'VS221101M',
                'product_name'=>'Jersey Monogram Logo Tee',
                'description'=> 'Since 1978, Gianni Versaces iconic Italian label has been celebrated for its over-the-top glamour and sexiness. After Giannis tragicdeath in 1997, his sister Donatella took the creative reins, and while remaining consistent with Giannis design aesthetic, Donatella has brought a bold femininity and subtle polish to the beloved design house.',
                'price'=>375,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/VS221101M.JPG',
                'categories' => 1,
                'product_type' => 1,
                'supplier' => 11,
                'brand'=> 11,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                'sku'=>'FG221101M',
                'product_name'=>'Perfect Vintage Tee',
                'description'=> 'Born in the streets of Los Angeles, Fear of God is a label from Creative Director and Founder, Jerry Lorenzo. Influenced by Lorenzo’s spirituality and diverse past, the collection combines both high fashion and street with an attention to detail using the finest materials.',
                'price'=>195,
                'discount'=>117 ,
                'like'=>0,
                'image'=>'images/shop/product/FG221101M.JPG',
                'categories' => 1,
                'product_type' => 1,
                'supplier' => 7,
                'brand'=> 7,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                'sku'=>'VS221101W',
                'product_name'=>'Logo T-Shirt',
                'description'=> 'Since 1978, Gianni Versaces iconic Italian label has been celebrated for its over-the-top glamour and sexiness. After Gianni"s tragic death in 1997, his sister Donatella took the creative reins, and while remaining consistent with Gianni"s design aesthetic, Donatella has brought a bold femininity and subtle polish to the beloved design house.',
                'price'=>575,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/VS221101W.jpg',
                'categories' => 1,
                'product_type' => 1,
                'supplier' => 11,
                'brand'=> 11,
                'gender' => 0,
                'status'=>1,
            ),
            array(
                'sku'=>'SL221101W',
                'product_name'=>'Boyfriend Fit Logo Crewneck Tee',
                'description'=> 'SAINT LAURENT has been influencing and revolutionizing the fashion industry since the debut of its iconic ‘Rive Gauche’ collection in 1966 - the couture house was the first to create a ready-to-wear capsule. The sleek, precisely tailored staples, like the signature biker jackets, transcend seasons and trends. Creative Director Anthony Vaccarello continues to honor the label’s illustrious reputation by reintroducing cult styles, including the ‘Lou’ handbag and ‘Tribute’ sandals.',
                'price'=>450,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/SL221101W.JPG',
                'categories' => 1,
                'product_type' => 1,
                'supplier' => 10,
                'brand'=> 10,
                'gender' => 0,
                'status'=>1,
            ),
            //POLO-Shirt
            array(
                'sku'=>'BB221101M',
                'product_name'=>'Walton Polo',
                'description'=> 'Founded in 1856, Burberry’s legacy as a pillar of British style grew from Thomas Burberry’s most iconic innovation: the gabardine trench coat. Upholding the pioneering spirit of his predecessor, current creative director Riccardo Tisci brings a fresh and irreverent approach to the house’s quintessentially British vision of luxury. Marrying technology, artistry, and tradition, the label touts a range of casual-wear and eveningwear that embodies a progressive femininity. Exquisite shirting, knitwear, and draped jackets exude refinement, while menswear-inspired polos, tailored trousers, and ankle boots achieve an easy polish.',
                'price'=>490,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/BB221101M.JPG',
                'categories' => 1,
                'product_type' => 1,
                'supplier' => 4,
                'brand'=> 4,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                'sku'=>'VS221102M',
                'product_name'=>'Versace Polo',
                'description'=> 'Since 1978, Gianni Versaces iconic Italian label has been celebrated for its over-the-top glamour and sexiness. After Giannis tragicdeath in 1997, his sister Donatella took the creative reins, and while remaining consistent with Giannis design aesthetic, Donatella has brought a bold femininity and subtle polish to the beloved design house.',
                'price'=>575,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/VS221102M.JPG',
                'categories' => 1,
                'product_type' => 1,
                'supplier' => 11,
                'brand'=> 11,
                'gender' => 1,
                'status'=>1,
            ),
            //Shirt
            array(
                'sku'=>'SL221201M',
                'product_name'=>'Classic Yves Shirt',
                'description'=> 'SAINT LAURENT has been influencing and revolutionizing the fashion industry since the debut of its iconic ‘Rive Gauche’ collection in 1966 - the couture house was the first to create a ready-to-wear capsule. The sleek, precisely tailored staples, like the signature biker jackets, transcend seasons and trends. Creative Director Anthony Vaccarello continues to honor the label’s illustrious reputation by reintroducing cult styles, including the ‘Lou’ handbag and ‘Tribute’ sandals.',
                'price'=>550,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/SL221201M.JPG',
                'categories' => 1,
                'product_type' => 2,
                'supplier' => 10,
                'brand'=> 10,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                'sku'=>'RL221201M',
                'product_name'=>'Oxford Shirt',
                'description'=> 'description',
                'price'=>99,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/RL221201M.jpg',
                'categories' => 1,
                'product_type' => 2,
                'supplier' => 8,
                'brand'=> 8,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                'sku'=>'VS221201M',
                'product_name'=>'Short Sleeve Printed Shirt',
                'description'=> 'Since 1978, Gianni Versaces iconic Italian label has been celebrated for its over-the-top glamour and sexiness. After Giannis tragicdeath in 1997, his sister Donatella took the creative reins, and while remaining consistent with Giannis design aesthetic, Donatella has brought a bold femininity and subtle polish to the beloved design house.',
                'price'=>1150,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/VS221201M.jpg',
                'categories' => 1,
                'product_type' => 2,
                'supplier' => 11,
                'brand'=> 11,
                'gender' => 1,
                'status'=>1,
            ),
            //PANTS
            array(
                'sku'=>'FG221301M',
                'product_name'=>'Slim Trouser',
                'description'=> 'Born in the streets of Los Angeles, Fear of God is a label from Creative Director and Founder, Jerry Lorenzo. Influenced by Lorenzo’s spirituality and diverse past, the collection combines both high fashion and street with an attention to detail using the finest materials.',
                'price'=>895,
                'discount'=>537,
                'like'=>0,
                'image'=>'images/shop/product/FG221301M.JPG',
                'categories' => 1,
                'product_type' => 3,
                'supplier' => 7,
                'brand'=> 7,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                'sku'=>'SL221301M',
                'product_name'=>'Saint Laurent Pant',
                'description'=> 'SAINT LAURENT has been influencing and revolutionizing the fashion industry since the debut of its iconic ‘Rive Gauche’ collection in 1966 - the couture house was the first to create a ready-to-wear capsule. The sleek, precisely tailored staples, like the signature biker jackets, transcend seasons and trends. Creative Director Anthony Vaccarello continues to honor the label’s illustrious reputation by reintroducing cult styles, including the ‘Lou’ handbag and ‘Tribute’ sandals.',
                'price'=>1550,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/SL221301M.JPG',
                'categories' => 1,
                'product_type' => 3,
                'supplier' => 10,
                'brand'=> 10,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                'sku'=>'RL221301M',
                'product_name'=>'Fleece Pant Relaxed',
                'description'=> 'ASDASD',
                'price'=>110,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/RL221301M.JPG',
                'categories' => 1,
                'product_type' => 3,
                'supplier' => 8,
                'brand'=> 8,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                
                'sku'=>'VS221301W',
                'product_name'=>'Gym Legging',
                'description'=> 'Since 1978, Gianni Versaces iconic Italian label has been celebrated for its over-the-top glamour and sexiness. After Gianni"s tragic death in 1997, his sister Donatella took the creative reins, and while remaining consistent with Gianni"s design aesthetic, Donatella has brought a bold femininity and subtle polish to the beloved design house.',
                'price'=>275,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/VS221301W.JPG',
                'categories' => 1,
                'product_type' => 3,
                'supplier' => 11,
                'brand'=> 11,
                'gender' => 0,
                'status'=>1,
            ),
            array(
                'sku'=>'SL221301W',
                'product_name'=>'Tailored Pants',
                'description'=> 'SAINT LAURENT has been influencing and revolutionizing the fashion industry since the debut of its iconic ‘Rive Gauche’ collection in 1966 - the couture house was the first to create a ready-to-wear capsule. The sleek, precisely tailored staples, like the signature biker jackets, transcend seasons and trends. Creative Director Anthony Vaccarello continues to honor the label’s illustrious reputation by reintroducing cult styles, including the ‘Lou’ handbag and ‘Tribute’ sandals.',
                'price'=>1150,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/SL221301W.JPG',
                'categories' => 1,
                'product_type' => 3,
                'supplier' => 10,
                'brand'=> 10,
                'gender' => 0,
                'status'=>1,
            ),
            //SHORTS
            array(
                'sku'=>'BB221301M',
                'product_name'=>'Guildes Small Scale Check Swim Trunk',
                'description'=> 'Founded in 1856, Burberry’s legacy as a pillar of British style grew from Thomas Burberry’s most iconic innovation: the gabardine trench coat. Upholding the pioneering spirit of his predecessor, current creative director Riccardo Tisci brings a fresh and irreverent approach to the house’s quintessentially British vision of luxury. Marrying technology, artistry, and tradition, the label touts a range of casual-wear and eveningwear that embodies a progressive femininity. Exquisite shirting, knitwear, and draped jackets exude refinement, while menswear-inspired polos, tailored trousers, and ankle boots achieve an easy polish.',
                'price'=>350,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/BB221301M.JPG',
                'categories' => 1,
                'product_type' => 3,
                'supplier' => 4,
                'brand'=> 4,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                'sku'=>'FG221302M',
                'product_name'=>'The Vintage Sweatshort',
                'description'=> 'Born in the streets of Los Angeles, Fear of God is a label from Creative Director and Founder, Jerry Lorenzo. Influenced by Lorenzo’s spirituality and diverse past, the collection combines both high fashion and street with an attention to detail using the finest materials.',
                'price'=>450,
                'discount'=>270,
                'like'=>0,
                'image'=>'images/shop/product/FG221302M.JPG',
                'categories' => 1,
                'product_type' => 3,
                'supplier' => 7,
                'brand'=> 7,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                'sku'=>'AD221301M',
                'product_name'=>'Adidas Originals X Noah Short',
                'description'=> 'ASDASD',
                'price'=>120,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/AD221301M.JPG',
                'categories' => 1,
                'product_type' => 3,
                'supplier' => 1,
                'brand'=> 1,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                'sku'=>'VS221302W',
                'product_name'=>'Coupe De Deaux Short',
                'description'=> 'Since 1978, Gianni Versaces iconic Italian label has been celebrated for its over-the-top glamour and sexiness. After Gianni"s tragic death in 1997, his sister Donatella took the creative reins, and while remaining consistent with Gianni"s design aesthetic, Donatella has brought a bold femininity and subtle polish to the beloved design house.',
                'price'=>1175,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/VS221302W.JPG',
                'categories' => 1,
                'product_type' => 3,
                'supplier' => 11,
                'brand'=> 11,
                'gender' => 0,
                'status'=>1,
            ),
            array(
                'sku'=>'AD221301W',
                'product_name'=>'True Pace Running Short',
                'description'=> 'ASDASD',
                'price'=>95,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/AD221301W.jpg',
                'categories' => 1,
                'product_type' => 3,
                'supplier' => 1,
                'brand'=> 1,
                'gender' => 0,
                'status'=>1,
            ),
            //Jackets
            array(
                'sku'=>'SL221401M',
                'product_name'=>'Teddy College Varsity Jacket',
                'description'=> 'SAINT LAURENT has been influencing and revolutionizing the fashion industry since the debut of its iconic ‘Rive Gauche’ collection in 1966 - the couture house was the first to create a ready-to-wear capsule. The sleek, precisely tailored staples, like the signature biker jackets, transcend seasons and trends. Creative Director Anthony Vaccarello continues to honor the label’s illustrious reputation by reintroducing cult styles, including the ‘Lou’ handbag and ‘Tribute’ sandals.',
                'price'=>2990,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/SL221401M.jpg',
                'categories' => 1,
                'product_type' => 4,
                'supplier' => 10,
                'brand'=> 10,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                
                'sku'=>'FG221401M',
                'product_name'=>'Souvenir Jacket',
                'description'=> 'Born in the streets of Los Angeles, Fear of God is a label from Creative Director and Founder, Jerry Lorenzo. Influenced by Lorenzo’s spirituality and diverse past, the collection combines both high fashion and street with an attention to detail using the finest materials.',
                'price'=>1295,
                'discount'=>544,
                'like'=>0,
                'image'=>'images/shop/product/FG221401M.JPG',
                'categories' => 1,
                'product_type' => 4,
                'supplier' => 7,
                'brand'=> 7,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                
                'sku'=>'BB221401M',
                'product_name'=>'Dainton Parka',
                'description'=> 'Founded in 1856, Burberry’s legacy as a pillar of British style grew from Thomas Burberry’s most iconic innovation: the gabardine trench coat. Upholding the pioneering spirit of his predecessor, current creative director Riccardo Tisci brings a fresh and irreverent approach to the house’s quintessentially British vision of luxury. Marrying technology, artistry, and tradition, the label touts a range of casual-wear and eveningwear that embodies a progressive femininity. Exquisite shirting, knitwear, and draped jackets exude refinement, while menswear-inspired polos, tailored trousers, and ankle boots achieve an easy polish.',
                'price'=>1690,
                'discount'=>845,
                'like'=>0,
                'image'=>'images/shop/product/BB221401M.jpg',
                'categories' => 1,
                'product_type' => 4,
                'supplier' => 4,
                'brand'=> 4,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                
                'sku'=>'SL221401W',
                'product_name'=>'Teddy Raglan Bomber Jacket',
                'description'=> 'SAINT LAURENT has been influencing and revolutionizing the fashion industry since the debut of its iconic ‘Rive Gauche’ collection in 1966 - the couture house was the first to create a ready-to-wear capsule. The sleek, precisely tailored staples, like the signature biker jackets, transcend seasons and trends. Creative Director Anthony Vaccarello continues to honor the label’s illustrious reputation by reintroducing cult styles, including the ‘Lou’ handbag and ‘Tribute’ sandals.',
                'price'=>2990,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/SL221401W.JPG',
                'categories' => 1,
                'product_type' => 4,
                'supplier' => 10,
                'brand'=> 10,
                'gender' => 0,
                'status'=>1,
            ),
            array(
                
                'sku'=>'BB221401W',
                'product_name'=>'Demmi Bomber',
                'description'=> 'Founded in 1856, Burberry’s legacy as a pillar of British style grew from Thomas Burberry’s most iconic innovation: the gabardine trench coat. Upholding the pioneering spirit of his predecessor, current creative director Riccardo Tisci brings a fresh and irreverent approach to the house’s quintessentially British vision of luxury. Marrying technology, artistry, and tradition, the label touts a range of casual-wear and eveningwear that embodies a progressive femininity. Exquisite shirting, knitwear, and draped jackets exude refinement, while menswear-inspired polos, tailored trousers, and ankle boots achieve an easy polish.',
                'price'=>1290,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/BB221401W.JPG',
                'categories' => 1,
                'product_type' => 4,
                'supplier' => 4,
                'brand'=> 4,
                'gender' => 0,
                'status'=>1,
            ),
            //Coats
            array(
                'sku'=>'BB221402M',
                'product_name'=>'Heritage Refresh Raglan Trench Coat',
                'description'=> 'Founded in 1856, Burberry’s legacy as a pillar of British style grew from Thomas Burberry’s most iconic innovation: the gabardine trench coat. Upholding the pioneering spirit of his predecessor, current creative director Riccardo Tisci brings a fresh and irreverent approach to the house’s quintessentially British vision of luxury. Marrying technology, artistry, and tradition, the label touts a range of casual-wear and eveningwear that embodies a progressive femininity. Exquisite shirting, knitwear, and draped jackets exude refinement, while menswear-inspired polos, tailored trousers, and ankle boots achieve an easy polish.',
                'price'=>2190,
                'discount'=>1424,
                'like'=>0,
                'image'=>'images/shop/product/BB221402M.JPG',
                'categories' => 1,
                'product_type' => 4,
                'supplier' => 4,
                'brand'=> 4,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                
                'sku'=>'FG221402M',
                'product_name'=>'Car Coat',
                'description'=> 'Born in the streets of Los Angeles, Fear of God is a label from Creative Director and Founder, Jerry Lorenzo. Influenced by Lorenzo’s spirituality and diverse past, the collection combines both high fashion and street with an attention to detail using the finest materials.',
                'price'=>1450,
                'discount'=>725,
                'like'=>0,
                'image'=>'images/shop/product/FG221402M.JPG',
                'categories' => 1,
                'product_type' => 4,
                'supplier' => 7,
                'brand'=> 7,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                'sku'=>'FG221403M',
                'product_name'=>'Camo Military Coat',
                'description'=> 'Born in the streets of Los Angeles, Fear of God is a label from Creative Director and Founder, Jerry Lorenzo. Influenced by Lorenzo’s spirituality and diverse past, the collection combines both high fashion and street with an attention to detail using the finest materials.',
                'price'=>995,
                'discount'=>498,
                'like'=>0,
                'image'=>'images/shop/product/FG221403M.JPG',
                'categories' => 1,
                'product_type' => 4,
                'supplier' => 7,
                'brand'=> 7,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                'sku'=>'BB221402W',
                'product_name'=>'Kensington Rain Jacket',
                'description'=> 'Founded in 1856, Burberry’s legacy as a pillar of British style grew from Thomas Burberry’s most iconic innovation: the gabardine trench coat. Upholding the pioneering spirit of his predecessor, current creative director Riccardo Tisci brings a fresh and irreverent approach to the house’s quintessentially British vision of luxury. Marrying technology, artistry, and tradition, the label touts a range of casual-wear and eveningwear that embodies a progressive femininity. Exquisite shirting, knitwear, and draped jackets exude refinement, while menswear-inspired polos, tailored trousers, and ankle boots achieve an easy polish.',
                'price'=>2490,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/BB221402W.JPG',
                'categories' => 1,
                'product_type' => 4,
                'supplier' => 4,
                'brand'=> 4,
                'gender' => 0,
                'status'=>1,
            ),
            array(
                'sku'=>'SL221402W',
                'product_name'=>'Leopard Jacket',
                'description'=> 'SAINT LAURENT has been influencing and revolutionizing the fashion industry since the debut of its iconic ‘Rive Gauche’ collection in 1966 - the couture house was the first to create a ready-to-wear capsule. The sleek, precisely tailored staples, like the signature biker jackets, transcend seasons and trends. Creative Director Anthony Vaccarello continues to honor the label’s illustrious reputation by reintroducing cult styles, including the ‘Lou’ handbag and ‘Tribute’ sandals.',
                'price'=>2550,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/SL221402W.JPG',
                'categories' => 1,
                'product_type' => 4,
                'supplier' => 10,
                'brand'=> 10,
                'gender' => 0,
                'status'=>1,
            ),
            //Denim
            array(
                'sku'=>'FG221501M',
                'product_name'=>'Denim Trucker Jacket',
                'description'=> 'Born in the streets of Los Angeles, Fear of God is a label from Creative Director and Founder, Jerry Lorenzo. Influenced by Lorenzo’s spirituality and diverse past, the collection combines both high fashion and street with an attention to detail using the finest materials.',
                'price'=>895,
                'discount'=>537,
                'like'=>0,
                'image'=>'images/shop/product/FG221501M.JPG',
                'categories' => 1,
                'product_type' => 5,
                'supplier' => 7,
                'brand'=> 7,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                'sku'=>'BA221501M',
                'product_name'=>'Oversized Jacket',
                'description'=> 'Creative director since 2015, Demna Gvasalia continues Balenciaga’s tradition of extreme experimentation, bringing his uniquely subversive vision to the storied French house. Merging the worlds of streetwear and high fashion, and blatantly disregarding industry conventions, Gvasalia reconfigures the label’s archival pieces with signature exaggerated silhouettes, asymmetric cuts, and acid colorways. Androgynous blazers, trench coats, and wool overcoats are cut in oversized shapes, while t-shirts, hoodies, and knitwear feature signature logo graphics.',
                'price'=>1573,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/BA221501M.JPG',
                'categories' => 1,
                'product_type' => 5,
                'supplier' => 3,
                'brand'=> 3,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                'sku'=>'BA221502M',
                'product_name'=>'Large Fit Paris Denim Jacker',
                'description'=> 'Creative director since 2015, Demna Gvasalia continues Balenciaga’s tradition of extreme experimentation, bringing his uniquely subversive vision to the storied French house. Merging the worlds of streetwear and high fashion, and blatantly disregarding industry conventions, Gvasalia reconfigures the label’s archival pieces with signature exaggerated silhouettes, asymmetric cuts, and acid colorways. Androgynous blazers, trench coats, and wool overcoats are cut in oversized shapes, while t-shirts, hoodies, and knitwear feature signature logo graphics.',
                'price'=>1590,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/BA221502M.JPG',
                'categories' => 1,
                'product_type' => 5,
                'supplier' => 3,
                'brand'=> 3,
                'gender' => 1,
                'status'=>1,
            ),
            array(
                'sku'=>'SL221501W',
                'product_name'=>'Sleeveless Denim Mini Dress',
                'description'=> 'SAINT LAURENT has been influencing and revolutionizing the fashion industry since the debut of its iconic ‘Rive Gauche’ collection in 1966 - the couture house was the first to create a ready-to-wear capsule. The sleek, precisely tailored staples, like the signature biker jackets, transcend seasons and trends. Creative Director Anthony Vaccarello continues to honor the label’s illustrious reputation by reintroducing cult styles, including the ‘Lou’ handbag and ‘Tribute’ sandals.',
                'price'=>1090,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/SL221501W.JPG',
                'categories' => 1,
                'product_type' => 5,
                'supplier' => 10,
                'brand'=> 10,
                'gender' => 0,
                'status'=>1,
            ),
            array(
                'sku'=>'SL221502W',
                'product_name'=>'Denim Jacket',
                'description'=> 'SAINT LAURENT has been influencing and revolutionizing the fashion industry since the debut of its iconic ‘Rive Gauche’ collection in 1966 - the couture house was the first to create a ready-to-wear capsule. The sleek, precisely tailored staples, like the signature biker jackets, transcend seasons and trends. Creative Director Anthony Vaccarello continues to honor the label’s illustrious reputation by reintroducing cult styles, including the ‘Lou’ handbag and ‘Tribute’ sandals.',
                'price'=>1090,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/SL221502W.jpg',
                'categories' => 1,
                'product_type' => 5,
                'supplier' => 10,
                'brand'=> 10,
                'gender' => 0,
                'status'=>1,
            ),
            //Luxury
            array(
                'sku'=>'RO222601W',
                'product_name'=>'Rose Gold Diamond Paved Watch',
                'description'=> '18kt rose gold case with a 18kt rose gold pearlmaster with diamonds bracelet. Fixed diamond set diamond paved bezel. Rose gold pave dial with gold-tone hands and Roman numeral hour markers. Dial Type: Analog. Date display at the 3 o"clock position. Rolex Calibre 2235 Automatic movement, containing 31 Jewels, bitting at 28800 vph, and has a power reserve of approximately 48 hours. Scratch resistant sapphire crystal. Screw down crown. Solid case back. Round case shape, case size: 34 mm, case thickness: 12 mm. Band width: 17 mm. Oyster clasp. Water resistant at 100 meters / 330 feet. Functions: date, hour, minute, second, chronometer. Luxury watch style. Watch label: Swiss Made. Item Variations: 81405rbr. Rolex Pearlmaster 34 Rose Gold Diamond Paved Watch 81405 rbr-0001.',
                'price'=>167700,
                'discount'=>140550,
                'like'=>0,
                'image'=>'images/shop/product/RO222601W.jpg',
                'categories' => 2,
                'product_type' => 6,
                'supplier' => 9,
                'brand'=> 9,
                'gender' => 0,
                'status'=>1,
            ),
            array(
                'sku'=>'CA222601W',
                'product_name'=>'Cartier Diamond Silver Watch',
                'description'=> 'Rose gold-tone 18kt rose gold case and bracelet. Fixed rose gold-tone bezel with diamond set 18kt rose gold. Silver-tone dial with blued-steel sword-shaped hands and Arabic & index hour markers. Minute scale around the inner rim. Dial Type: Analog. Automatic movement. Scratch resistant sapphire crystal. Pull / push crown. Solid case back. Round case shape, case size: 42 mm, case thickness: 9 mm. Hidden clasp. Water resistant at 30 meters / 100 feet. Functions: hour, minute, second. Cartier Pasha Series. Luxury watch style. Watch label: Swiss Made. Pre-owned Cartier Cartier Pasha Automatic Diamond Silver Dial Ladies Watch 2770.',
                'price'=>35795,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/CA222601W.jpg',
                'categories' => 2,
                'product_type' => 6,
                'supplier' => 5,
                'brand'=> 5,
                'gender' => 0,
                'status'=>1,
            ),
            array(
                'sku'=>'RO222601M',
                'product_name'=>'Cosmograph Daytona Eye Diamond Watch',
                'description'=> '18kt rose gold case with a black rubber oysterflex strap. Fixed diamond set bezel. Yellow-tone dial with gold-tone hands and diamond hour markers. Dial Type: Analog. Chronograph - three sub-dials displaying: 60 second, 30 minute and 12 hour. Rolex Calibre 4130 automatic movement with a 72-hour power reserve. Scratch resistant sapphire crystal. Screw down crown. Solid case back. Round case shape, case size: 40 mm, case thickness: 12.4 mm. Band width: 20 mm. Oysterlock clasp. Water resistant at 100 meters / 330 feet. Functions: chronograph, hour, minute, small second, chronometer. Additional Info: original box, international warranty card, manual (complete accessories). Luxury watch style. Watch label: Swiss Made. Rolex Cosmograph Daytona Eye of the Tiger Chronograph Automatic Chronometer Diamond Men"s Watch 116588TBR-0003.',
                'price'=>400000,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/RO222601M.jpg',
                'categories' => 2,
                'product_type' => 6,
                'supplier' => 9,
                'brand'=> 9,
                'gender' => 1,
                'status'=>1,
            ),
            //Sport
            array(
                'sku'=>'AP222701M',
                'product_name'=>'Royal Oak "China Edition" Watch',
                'description'=> 'Grey titanium case and bracelet. Fixed silver-tone titanium bezel. Slate get dial with grey hands and index hour markers. Week number markers around the outer rim. Dial Type: Analog. Luminescent hands and markers. Perpetual calendar. Four sub-dials displaying: month/leap year, moonphase, date, day of the week. Audemars Piguet Calibre 5134 Automatic movement, based upon Audemars Piguet 2120, containing 38 Jewels, composed of 374 parts, bitting at 19800 vph, and has a power reserve of approximately 40 hours. Scratch resistant sapphire crystal. Screw down crown. Transparent see through case back. Round case shape, case size: 41 mm, case thickness: 9.5 mm. Deployment clasp. Water resistant at 20 meters / 66 feet. Functions: perpetual calendar, moon phase, week number, leap year, month, date, day, hour, minute. Additional Info: limited edition of 88. Royal Oak Perpetual Calendar Series. Sport watch style. Watch label: Swiss Made. Audemars Piguet Royal Oak "China Edition" Perpetual Calendar Automatic Men"s Watch 26609TI.OO.1220TI.01.',
                'price'=>200000,
                'discount'=>0,
                'like'=>0,
                'image'=>'images/shop/product/AP222701M.jpg',
                'categories' => 2,
                'product_type' => 7,
                'supplier' => 2,
                'brand'=> 2,
                'gender' => 1,
                'status'=>1,
            ),
        );
        for( $i = 0;  $i < count($values);  $i++ ){
            Product::create($values[$i]);
        }
        
        
    }
}
